package ox.utils;

import ox.Configuration;

/**
 * @author Fernando Nogueira
 * @since 4/14/14 3:23 PM
 */
public final class Log {

    /**
     * Utility class
     */
    private Log() {
    }

    /**
     * Adds a preffix to help identify logs generated by this module
     *
     * @param logMsg
     * @return
     */
    public static String preff(String logMsg) {
        return Configuration.MODULE_TAG + " " + logMsg;
    }

}
